### ISSUE TITLE
`wyvern ls`  returns 100 games when I have 492

### ISSUE THREAD

**Issue by fmestevez** [nicohman/wyvern#2]
I'm guessing it's not taking pagination into account?
There's exactly 100 games per page in the store's game list.

OS info:
```
 ██████████████████  ████████     bant@floyd
 ██████████████████  ████████     OS: Manjaro 18.0.2 Illyria
 ██████████████████  ████████     Kernel: x86_64 Linux 4.14.94-1-MANJARO
 ██████████████████  ████████     Uptime: 37m
 ████████            ████████     Packages: 1280
 ████████  ████████  ████████     Shell: zsh 5.6.2
 ████████  ████████  ████████     Resolution: 1920x1200
 ████████  ████████  ████████     WM: i3
 ████████  ████████  ████████     GTK Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Adapta-Nokto-Maia
 ████████  ████████  ████████     Font: Noto Sans 10
 ████████  ████████  ████████     CPU: Intel Core i7-7500U @ 4x 3.5GHz [54.0°C]
 ████████  ████████  ████████     GPU: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
 ████████  ████████  ████████     RAM: 5965MiB / 24007MiB
```

**Comment by nicohman** [comment]
Yup, looks like it was due to pagination. I just pushed a commit to master that *should* resolve the issue. Would you mind cloning it and telling me if it fixes your problem? I don't have enough games on GOG to tell. Thanks and sorry for the inconvenience.

**Comment by nicohman** [comment]
Assuming that this fix worked and resolving issue.

**Comment by mcphail** [comment]
Hi.

I'm still getting a list which is truncated at 100 games when building from the current `master`. Would you reopen this issue? Thanks.

**Comment by nicohman** [comment]
Thanks for letting me know that this issue is still persisting! I pushed a possible fix to the GOG library's master. If you add `, rev = "a6fb074a"` to the GOG dependency in `Cargo.toml` to force it to fetch the latest version and try building again, does it work now?

**Comment by mcphail** [comment]
I've just tried the snapped version you've released (yay!) on my raspberry pi, and that seems to work. Thanks! No idea why the version I built last night didn't pick this up, so apologies for the noise.

**Comment by sigboe** [comment]
@mcphail Does the snapped version require you to install a package manager like Ubuntu Snaps?

**Comment by mcphail** [comment]
> @mcphail Does the snapped version require you to install a package manager like Ubuntu Snaps?

Yes. You need to install snapd. See the instructions at https://docs.snapcraft.io/installing-snapd/6735 if you want to give it a try. The snap isn't a fully functional way to use wyvern yet, though, so some things won't work properly. I'm going to try to polish the snap support so it becomes an acceptable alternative to compiling.
